### ISSUE TITLE
doctype problem

### ISSUE THREAD

**Issue by arosas** [heygrady/textshadow#10]
I was wondering why is it breaking when I use the following doctype
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

but using the latest html5 doctype works is this a known issue?

**Comment by heygrady** [comment]
see #8
