### ISSUE TITLE
Works in IE7, but not in IE8 or 9

### ISSUE THREAD

**Issue by msuemnig** [heygrady/textshadow#12]
See the screenshots for what I'm getting.  Just wondering if you're interested in helping me troubleshoot why I can't get your library to work in anything buy IE7

Thanks in advance, if you decide to help!
![Export-for-Grady](https://f.cloud.github.com/assets/3431370/304935/34ee305a-964b-11e2-902e-beda14252b39.png)

**Comment by heygrady** [comment]
It's really frustrating that you pasted a picture of your code when you can easily just include the code here. A picture of code is fairly useless.

If you want me to do anything, paste your code here.

Also, I just ran a quick test and my code is working in IE7-IE9 exactly as expected.

Please don't use the transitional doctype. Here's an article from 2006 explaining why you should stop using it: http://www.456bereastreet.com/archive/200609/no_more_transitional_doctypes_please/
