### ISSUE TITLE
I cant see text shadow in IE :(

### ISSUE THREAD

**Issue by ganeshkondalkar** [heygrady/textshadow#2]
Hi there,

Thanks for creating such a nice JS plugin which enables the text-shadow for IE < 9. However I think I have missed one of the steps mentioned by you and that is why I wont get the same output as FF/chrome.

I can't see any text-shadows around the text in IE9-8-7. :(

Could you please guide me?

Actually, I wont understood this line in the "readme.md file"
"h1 .ui-text-shadow-copy {}"

Check my Code:
http://pastebin.com/raw.php?i=db3UkZGR

Thanks in advance! 

Ganesh Kondalkar (Mumbai - India) 
ganeshkondalkar@gmail.com

**Comment by heygrady** [comment]
You need to put your script below your content, just above your `</body>`.

**Comment by ganeshkondalkar** [comment]
Thanks a lot Heygrady! :)

I tried it and now its working in IE. :)
