### ISSUE TITLE
Text being cropped. Unicode problem?

### ISSUE THREAD

**Issue by JonMcL** [heygrady/textshadow#3]
Hello,

Thanks for all the work on this plugin.

Unfortunately, we just noticed a problem where some of the Russian words (Cyrillic text) seem to be getting cropped in IE9.

I put together a jsFiddle to demonstrate:

http://jsfiddle.net/JonMcL/wWvSw/

On IE9, if you look at the 3rd line of white text, you will likely see just:
  компании Gazprom International, Управл
but it should be:
  компании Gazprom International, Управляющий

4th line:
  директор и Председатель Наблюдательного Со
but it should be:
  директор и Председатель Наблюдательного Совета

Any suggestions?

Thanks!!

..jon

**Comment by heygrady** [comment]
This is possibly a unicode or a regular expression issue. I'll look into it.

**Comment by JonMcL** [comment]
Working great!

Thanks!!

Working jsFiddle: http://jsfiddle.net/JonMcL/wWvSw/10/
